# Generated by Django 4.2.5 on 2025-06-21 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="姓名"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system_admin", "系统管理员"),
                            ("doctor", "医生"),
                            ("drug_admin", "药品管理员"),
                            ("patient", "患者"),
                            ("pharma_admin", "药企管理员"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="账户是否激活"),
                ),
                (
                    "is_superadmin",
                    models.BooleanField(default=False, verbose_name="超级管理员"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="注册时间"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="core_user_groups",
                        to="auth.group",
                        verbose_name="用户组",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="core_user_permissions",
                        to="auth.permission",
                        verbose_name="用户权限",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user",
            },
        ),
    ]
