# Generated by Django 4.2.5 on 2025-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_admin", "系统管理员"),
                    ("doctor", "医生"),
                    ("drug_admin", "药品管理员"),
                    ("patient", "患者"),
                    ("pharma_admin", "药企管理员"),
                ],
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
