# Generated by Django 4.2.5 on 2025-06-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="药品名称")),
                (
                    "spec",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="类别"
                    ),
                ),
                (
                    "expiration",
                    models.DateField(blank=True, null=True, verbose_name="有效期"),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="生产商"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="通用名"
                    ),
                ),
                (
                    "approval_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="批准文号"
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="剂型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("pending", "待审核"),
                            ("inactive", "停用"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "storage_condition",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="储存条件"
                    ),
                ),
                (
                    "shelf_life",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="有效期(月)"
                    ),
                ),
                (
                    "otc_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prescription", "处方药"),
                            ("otc_red", "甲类非处方药"),
                            ("otc_green", "乙类非处方药"),
                            ("not_otc", "非OTC"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="OTC类型",
                    ),
                ),
                (
                    "medical_insurance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("class_a", "甲类"),
                            ("class_b", "乙类"),
                            ("class_c", "丙类"),
                            ("not_covered", "非医保"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="医保类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "药品",
                "verbose_name_plural": "药品",
                "db_table": "drug",
            },
        ),
        migrations.CreateModel(
            name="Pharma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("合作中", "合作中"),
                            ("待审核", "待审核"),
                            ("已终止", "已终止"),
                        ],
                        default="待审核",
                        max_length=20,
                    ),
                ),
                ("founded", models.DateField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "药企",
                "verbose_name_plural": "药企",
                "db_table": "pharma",
            },
        ),
        migrations.CreateModel(
            name="PharmaGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PharmaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WarningLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="警告信息"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "预警日志",
                "verbose_name_plural": "预警日志",
                "db_table": "warning_log",
            },
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "batch_code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="批次号",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, null=True, verbose_name="数量"),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.drug",
                        verbose_name="药品",
                    ),
                ),
                (
                    "pharma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.pharma",
                        verbose_name="药企",
                    ),
                ),
            ],
            options={
                "verbose_name": "药品供应",
                "verbose_name_plural": "药品供应",
                "db_table": "supply",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.IntegerField(default=0, verbose_name="当前库存"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_inventories",
                        to="hospital.hospital",
                        verbose_name="医院",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存",
                "verbose_name_plural": "库存",
                "db_table": "supply_inventory",
            },
        ),
        migrations.CreateModel(
            name="PharmaDrugSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supply_start_date", models.DateField(verbose_name="供应开始日期")),
                (
                    "supply_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="供应结束日期"
                    ),
                ),
                (
                    "is_primary_supplier",
                    models.BooleanField(default=False, verbose_name="是否为主要供应商"),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="资质证书编号",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.drug",
                        verbose_name="药品",
                    ),
                ),
                (
                    "pharma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.pharma",
                        verbose_name="药企",
                    ),
                ),
            ],
            options={
                "verbose_name": "药企药品供应关系",
                "verbose_name_plural": "药企药品供应关系",
                "db_table": "pharma_drug_supply",
                "unique_together": {("pharma", "drug")},
            },
        ),
    ]
