# Generated by Django 4.2.5 on 2025-06-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="drug",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="supply.drug",
                verbose_name="药品",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventory",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="hospital.hospital",
                verbose_name="医院",
            ),
        ),
    ]
