# Generated by Django 4.2.5 on 2025-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0002_inventory_drug_alter_inventory_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="warning_threshold",
            field=models.IntegerField(default=100, verbose_name="预警阈值"),
        ),
    ]
