# Generated by Django 4.2.5 on 2025-06-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supply", "0001_initial"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "sale_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="销售编号",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="状态"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.drugadmin",
                        verbose_name="药品管理员",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.drug",
                        verbose_name="药品",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospital",
                        verbose_name="医院",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售记录",
                "verbose_name_plural": "销售记录",
                "db_table": "sale",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "purchase_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="采购编号",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="状态"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.drugadmin",
                        verbose_name="药品管理员",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.drug",
                        verbose_name="药品",
                    ),
                ),
                (
                    "pharma",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supply.pharma",
                        verbose_name="药企",
                    ),
                ),
            ],
            options={
                "verbose_name": "进货记录",
                "verbose_name_plural": "进货记录",
                "db_table": "purchase",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开药时间"
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="用法"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.doctor",
                        verbose_name="医生",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.drug",
                        verbose_name="药品",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "用药记录",
                "verbose_name_plural": "用药记录",
                "db_table": "prescription",
            },
        ),
    ]
