# Generated by Django 4.2.5 on 2025-06-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="hospital",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.hospital",
                verbose_name="医院",
            ),
            preserve_default=False,
        ),
    ]
