# Generated by Django 4.2.5 on 2025-06-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_purchase_hospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已审核"),
                    ("received", "已入库"),
                    ("rejected", "已拒绝"),
                ],
                default="pending",
                help_text="进货单当前状态",
                max_length=50,
                verbose_name="状态",
            ),
        ),
    ]
