# Generated by Django 4.2.5 on 2025-06-15 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_alter_purchase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="状态"
            ),
        ),
    ]
