# Generated by Django 4.2.5 on 2025-06-21 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="医院名称")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="等级"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="类型"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所在城市"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="医院简介"),
                ),
                (
                    "founded",
                    models.DateField(blank=True, null=True, verbose_name="成立日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("合作中", "合作中"),
                            ("待审核", "待审核"),
                            ("已终止", "已终止"),
                        ],
                        default="待审核",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "医院",
                "verbose_name_plural": "医院",
                "db_table": "hospital",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birth",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "患者",
                "verbose_name_plural": "患者",
                "db_table": "patient",
            },
        ),
        migrations.CreateModel(
            name="DrugAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "employee_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="员工编号"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospital",
                        verbose_name="医院",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "药品管理员",
                "verbose_name_plural": "药品管理员",
                "db_table": "drug_admin",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="职称"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospital",
                        verbose_name="医院",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "医生",
                "verbose_name_plural": "医生",
                "db_table": "doctor",
            },
        ),
    ]
