# Generated by Django 4.2.5 on 2025-06-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="contact",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="联系方式"
            ),
        ),
    ]
